### ISSUE TITLE
The translation of tall dragon tree is missing.

### ISSUE THREAD

**Issue by Mechalopa** [Pandarix/VerdantVibes#4]
![2023-11-11_18 21 14](https://github.com/Pandarix/VerdantVibes/assets/92443696/a2990b5b-f75c-4f95-8629-218c543b0f97)

**Comment by Pandarix** [comment]
Resolved in [commit eed7488](https://github.com/Pandarix/VerdantVibes/commit/eed7488b35dea43ea5212f60009acabb49265037). Will be present in the next update.

Thank you for reporting!
