### ISSUE TITLE
Mismatched item

### ISSUE THREAD

**Issue by AudibleWallpaper** [Pandarix/VerdantVibes#5]
When right clicking a blue lobelia out of a flower pot, a money tree is returned instead.

**Comment by Pandarix** [comment]
Could reproduce and found the issue. Will be fixed in the next update that will release very soon.
I'll reply with the updated version's download and close this issue once the update is released.

Thanks for reporting!

**Comment by Pandarix** [comment]
Fixed in 1.0.2 :)
https://curseforge.com/minecraft/mc-mods/verdantvibes/files
