### ISSUE TITLE
Crash on World Generation

### ISSUE THREAD

**Issue by lanwoodall423** [Pandarix/VerdantVibes#6]
Following the update today I get a crash on world generation.
[crash-2023-11-23_00.00.17-server.txt](https://github.com/Pandarix/VerdantVibes/files/13446151/crash-2023-11-23_00.00.17-server.txt)
[latest.log](https://github.com/Pandarix/VerdantVibes/files/13446153/latest.log)

Disabling VerdantVibes fixes the issue. 
Reverting to 1.0.1 fixes the issue.

**Comment by Pandarix** [comment]
Could reproduce. Seems to be an incompatibility issue because `William Wythers' Expanded Ecosphere` is changing the generation.
After installing `Cyanide` I could expand the error log to:

> Description: Exception generating new chunk
> 
> com.alcatrazescapee.cyanide.codec.FeatureCycleDetector$FeatureCycleException: A feature cycle was found.
> 
> Cycle:
> At step 9
> Feature 'verdantvibes:cattails'
>   must be before 'verdantvibes:cattails' (defined in 'wythers:flooded_savanna' at index 10, 11)

I most likely found the issue and will be working on it asap. Thank you for reporting!

**Comment by Pandarix** [comment]
I actually actively tried to prevent it, but I just missed one single JSON line.

Both `cattails` and `cattails_swamp` were using the `cattails` and not `cattails` & `cattails_swamp` configured feature, resulting in this feature cycle.

After changing the `biome_modifier` of `cattails_swamp` to use the swamp-feature, the world generates just fine again. I will upload these changes immediately.

**Comment by Pandarix** [comment]
You can now download version 1.0.3 that fixes this issue. Sorry for the inconvenience!

https://curseforge.com/minecraft/mc-mods/verdantvibes/files
https://modrinth.com/mod/verdantvibes/versions

I will archive version 1.0.2 to prevent people downloading a broken version.
