### ISSUE TITLE
Can't seem to load mod on server

### ISSUE THREAD

**Issue by Ladocterus** [Pandarix/VerdantVibes#7]
I'm on forge 1.20.1, and I can't seem to load the mod on a server
[server launc crash.txt](https://github.com/Pandarix/VerdantVibes/files/13464367/server.launc.crash.txt)

**Comment by Pandarix** [comment]
Hi, it seems that I've somehow didn't separate client and server functionality enough. The Particleengine seems to be the issue.

I'm currently not able to fix it right away. For now, please use Version 1.0.1. I'll hopefully be able to fix this issue tomorrow, so then you can just update it :).

Sorry for the inconvenience!

**Comment by Pandarix** [comment]
fixed in version 1.0.4
